version: '3.8'

services:
  # Redis for message broker and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ASCEP Backend
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Price Feed Service
  price_feeds:
    build: .
    command: python price_feed_service.py
    environment:
      - RAILWAY_STATIC_URL=http://backend:5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - backend
    restart: unless-stopped

  # Celery Worker
  celery:
    build: .
    command: celery -A backend.celery_worker.celery_app worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - backend
    restart: unless-stopped

volumes:
  redis_data: 