[phases.setup]
nixPkgs = ["python311", "nodejs_18", "redis"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd frontend && pnpm run build"
]

[start]
cmd = "./start_microservices.sh" 